version: "3"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  web:
    command: "python src/manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUNBUFFERED: 1
      HASHID_SALT: "123456"
    build: src/
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  dev_volume:
    driver: local
